Controllers/AdministrationController.cs
using Competition_PRO.Data.Models;
using Competition_PRO.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Competition_PRO.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly RoleManager<ApplicationRole> roleManager;

        public AdministrationController(RoleManager<ApplicationRole> roleManager)
        {
            this.roleManager = roleManager;
        }
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            ApplicationRole identityRole = new ApplicationRole
            {
                Name = model.RoleName
            };
            var result = await roleManager.CreateAsync(identityRole);
            if (result.Succeeded)
            {
                return Redirect("/");
            }
            else
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            return View(model);
        }
    }

}

Controllers/LeaderboardController.cs
using Competition_PRO.Data;
using Competition_PRO.Data.Models;
using Competition_PRO.Models;
using Competition_PRO.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Competition_PRO.Controllers
{
    public class LeaderboardController : Controller
    {
        public IActionResult Mechanic()
        {
            return this.View();
        }
    }
}

Controllers/TeamController.cs
using Competition_PRO.Data;
using Competition_PRO.Data.Models;
using Competition_PRO.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Competition_PRO.Controllers
{
    public class TeamController : Controller
    {
        private readonly ApplicationDbContext db;
        private enum Role { mechanic1, mechanic2, driver, leader };
        private Role role;

        public TeamController(ApplicationDbContext db)
        {
            this.db = db;
        }
        public IActionResult Create()
        {
            return this.View();
        }
        [HttpPost]
        public IActionResult Create(TeamInputModel input)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }
            Team team = new Team { ShortName = input.ShortSchoolName };
            int index = 1;
            foreach (var item in input.Names)
            {
                switch (index)
                {
                    case 1: role = Role.mechanic1; break;
                    case 2: role = Role.mechanic2; break;
                    case 3: role = Role.driver; break;
                    default: break;
                }
                team.TeamParticipants.Add(new TeamParticipant
                {
                    Name = item,
                    Role = (int)role,
                });
                index++;
            }
            team.TeamParticipants.Add(new TeamParticipant
            {
                Name = input.LeaderName,
                Role = (int)Role.leader,
            });

            this.db.Teams.Add(team);
            this.db.SaveChanges();
            return this.Redirect("/");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" style="font-size: 16px;">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Competition Pro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/nicepage.css" />
    <link rel="stylesheet" href="~/css/Burgers-1.css" />


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="​breakfast">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Burgers 1</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
    <link rel="stylesheet" href="Burgers-1.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery-1.9.1.min.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 4.5.6, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i|Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Kalam:300,400,700|Alata:400">


    <script type="application/ld+json">        {

                "name": "",
                "logo": "images/default-logo.png"
        }</script>
    <meta name="theme-color" content="#18922c">
    <meta property="og:title" content="Burgers 1">
    <meta property="og:type" content="website">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Competition Pro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Create">Регистрация на отбор</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Състезание</a>
                        </li>
                        <div class="dropdown">
                            <button class="dropbtn">
                                Dropdown
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="dropdown-content">
                                <a href="#">Link 1</a>
                                <a href="#">Link 2</a>
                                <a href="#">Link 3</a>
                            </div>
                        </div>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leaderboard" asp-action="Mechanic">Класиране</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Контакти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="CreateRole">aaaa</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        <hr id="hr-home" />
    </header>
    <div class="container body-white">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Competition Pro
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>